// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"Go-001/Week04/pto/api/controllers"
	"Go-001/Week04/pto/api/domain"
	"Go-001/Week04/pto/api/repository"
)

// Injectors from wire.go:

func InitTicketController() controllers.TicketController {
	ticketRepo := repository.NewTicketRepo()
	ticket := domain.NewTicket(ticketRepo)
	ticketController := controllers.NewTicketController(ticket)
	return ticketController
}
